### PR TITLE
Breaking dependencies update

### PR DESCRIPTION
**Pull request by danibix95**
The work provided in this pull request allows **lc39** to support [`fastify`](https://github.com/fastify/fastify/) v3.

**Changes:**
- updated _fastify_ to latest version, moving to the v3 potentially dependencies breaking release
- updated _fastify_ plugins accordingly to support fastify v3
- updated _commander_ to latest version
- updated custom logger to not use the underlying `IncomingMessage` object, that corresponds to the new `raw` field of [`Request`](https://github.com/fastify/fastify/blob/master/docs/Request.md) and [`Reply`](https://github.com/fastify/fastify/blob/master/docs/Reply.md) objects. In this manner, logged values are safely extracted only from fastify objects.

**Notes:**
- _commander_ migration tips for version 4.x.x suggest to change code like
  ```javascript
  if (!program.args.length) ...
  ```

    with

  ```javascript
  if (program.rawArgs.length < 3) ...
  ```
    However, upgrading _commander_ to latest version does not affect **lc39** code behavior, since it still expects only an argument that is different from parsed options (which are removed from `program.args` variable by the parsing procedure).
- **lc39** code has been read following the details provided both in fastify and fastify plugins changelogs and in the [migration guide](https://github.com/fastify/fastify/blob/master/docs/Migration-Guide-V3.md). Nonetheless, it is _recommended_ to read the migration guide before merging this pull request to verify that the work provided here covers all the changes that affect **lc39** library.

**Regressions:**
- for the moment **no** bugs nor incompatibilities have been introduced with the update. However, a follow up of this work is to revise the [`custom-plugin-lib`](https://github.com/mia-platform/custom-plugin-lib) to verify that is compatible with fastify v3

#### Checklist

- [x] your branch will not cause merge conflict with `master`
- [x] run `npm test`
- [ ] tests are included
- [ ] the documentation is updated or integrated accordingly with your changes _(no doc update is needed for the moment)_
- [x] the code will follow the lint rules and style of the project
- [x] you are not committing extraneous files or sensible data

#### Notify to

@fredmaggiowski

### CODE REVIEW

**Comment by fredmaggiowski** [comment]
Hi @danibix95, thanks for your contribution.

I've read the migration guide and your changes seems fine. Have you tried running the examples?

Also, has there been any change concerning route and plugins registration in fastify 3?

Not that it's a problem but I'm afraid merging this PR will bring us lc39 v4 :)

**Comment by davidebianchi** [comment]
We should try to integrate this version of lc39 into [custom-plugin-lib](https://github.com/mia-platform/custom-plugin-lib) as suggested. 

I've read the migration guide to fastify v3, and it is a breaking change also for lc39, for example (but not only) for the changes in plugins usage.

**Comment by danibix95** [comment]
I have tried running the example and everything works fine (routes, swagger, metrics, health checks). I also tried upgrading the lib fastify-env of the example to the latest one to check that it works also with the support for fastify v3.

According to the release notes of the different fastify libraries, it doesn't appear that it has been performed any modification related to routes and plugins registration (except for the middleware handling, but it should not affect `lc39`).
Nonetheless, I need to also check the compatibility of fastify v3 with the `custom-plugin-lib`.

May I suggest to change the destination branch of this PR from `master` to a new one, something like `v4`, so that it can be released in the final code only at the appropriate moment? In this manner it would be possible continue developing current version of `lc39`, while further tests can be performed on the support of fastify v3 for `lc39` and `custom-plugin-lib`.

**Comment by davidebianchi** [comment]
Yes sorry, I said plugins but I meant middleware 😄, but also for changes in schema registration for example. 

This lib is highly coupled with fastify, so if the fastify usage change the final user of lc39 will be impacted.

It may be a good idea, but instead of a v4 branch I'd like to start a v3.x branch to support and in master merge this changes with the upgrade of fastify version and release a `v4-alpha` version from master

**Comment by danibix95** [comment]
Hi @davidebianchi, I further updated lc39 library to include latest Fastify changes.

Meanwhile, I have been able to update the [custom-plugin-lib](https://github.com/mia-platform/custom-plugin-lib) to use Fastify v3 and this lc39 update. However, current changes are not ready to be committed because latest lc39 updates have not been published yet. In fact, I had to "install" the local version of lc39 to test the custom-plugin-lib.

Would it be possible to create a beta release of lc39 library, so that I can also commit the changes I made to the custom-plugin-lib?

**Comment by davidebianchi** [comment]
Hi @danibix95 , great news! Of course it is possible!
I try to publish the rc version in the weekend, I'll write here when it's published.

**Review by davidebianchi — APPROVED** [review]
LGTM

**Comment by davidebianchi** [comment]
I merged and tagged the `4.0.0-rc.0` version. It is possible to download and use it from npm using the `@next` tag:

`npm i --save @mia-platform/lc39@next`

**Pull request merged**
